"""Add wallet schema

Revision ID: 16e7df31b615
Revises: 6e7305308ef2
Create Date: 2026-02-21 19:15:51.034022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e7df31b615'
down_revision = '6e7305308ef2'
branch_labels = None
depends_on = None


def upgrade():
    # Drop index and table only if they exist (handles DB drift)
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_message_status'), if_exists=True)

    # Check if table exists before dropping
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    if 'contact_message' in existing_tables:
        op.drop_table('contact_message')

    if 'contactmessage' in existing_tables:
        with op.batch_alter_table('contactmessage', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_contactmessage_status'), if_exists=True)
        op.drop_table('contactmessage')

    # This is the real work — add wallet schema to transactions
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_foreign_key('fk_transactions_wallet_id', 'wallets', ['wallet_id'], ['id'])
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('wallet_id')

    op.create_table('contactmessage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('category', sa.VARCHAR(length=200), nullable=False),
    sa.Column('message', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contactmessage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contactmessage_status'), ['status'], unique=False)

    op.create_table('contact_message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('category', sa.VARCHAR(length=200), nullable=False),
    sa.Column('message', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_message_status'), ['status'], unique=False)

    # ### end Alembic commands ###
