"""Add timezone awareness to all datetime columns

Revision ID: 4b052c64176f
Revises: 
Create Date: 2026-01-14 13:13:31.621142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b052c64176f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verification_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('last_login',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('verification_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
