"""Modify transaction model

Revision ID: 6e7305308ef2
Revises: 8c56315e72df
Create Date: 2026-02-18 20:23:16.620538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7305308ef2'
down_revision = '8c56315e72df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_tx_user_id'))
        batch_op.create_index('idx_tx_user_id', ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index('idx_tx_user_id')
        batch_op.create_index(batch_op.f('idx_tx_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
